CREATE OR REPLACE PROCEDURE MIGRATE_BCM_DATA AS
BEGIN
    -- Insert into SUPPLIERS table
    INSERT INTO SUPPLIERS (SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_EMAIL, SUPP_STREET, SUPP_TOWN, SUPP_COUNTRY)
    SELECT DISTINCT SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_EMAIL,
           REGEXP_SUBSTR(SUPP_ADDRESS, '^[^,]+'), -- Extract street
           REGEXP_SUBSTR(SUPP_ADDRESS, '\s*([^,]+)', 1, 2), -- Extract town
           REGEXP_SUBSTR(SUPP_ADDRESS, '\s*([^,]+)$') -- Extract country
    FROM BCM_ORDER_MGT
    WHERE SUPPLIER_NAME IS NOT NULL; -- Ensure supplier name is not null
    
    -- Insert into SUPPLIERCONTACTS table
    INSERT INTO SUPPLIER_CONTACTS (SUPPLIER_ID, CONTACT_NUMBER)
    SELECT DISTinct S.SUPPLIER_ID, REGEXP_SUBSTR(B.SUPP_CONTACT_NUMBER, '[^,]+', 1) CONTACT_NUMBER
    FROM BCM_ORDER_MGT B
    JOIN SUPPLIERS S ON B.SUPPLIER_NAME = S.SUPPLIER_NAME;
        
    -- Insert into ORDERS table
    INSERT INTO ORDERS (ORDER_REF, ORDER_DATE, SUPPLIER_ID, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS)
    SELECT DISTINCT B.ORDER_REF, TO_DATE(ORDER_DATE, 'DD-MON-YYYY') ORDER_DATE, S.SUPPLIER_ID,
           TO_NUMBER(REPLACE(ORDER_TOTAL_AMOUNT, ',', '')) ORDER_TOTAL_AMOUNT, B.ORDER_DESCRIPTION, B.ORDER_STATUS
    FROM BCM_ORDER_MGT B
    JOIN SUPPLIERS S ON B.SUPPLIER_NAME = S.SUPPLIER_NAME
    WHERE B.ORDER_REF NOT LIKE '%-%'; -- Exclude order lines
    
    -- Insert into INVOICES table
    INSERT INTO INVOICES (ORDER_ID, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION)
    SELECT O.ORDER_ID, B.INVOICE_REFERENCE, TO_DATE(B.INVOICE_DATE, 'DD-MON-YYYY') INVOICE_DATE,
        B.INVOICE_STATUS, B.INVOICE_HOLD_REASON,
        TO_NUMBER(REPLACE(B.INVOICE_AMOUNT, ',', '')) INVOICE_AMOUNT,  B.INVOICE_DESCRIPTION
    FROM BCM_ORDER_MGT B
    JOIN ORDERS O ON B.ORDER_REF = O.ORDER_REF;
    
    -- Insert into ORDER_LINES table
    INSERT INTO ORDER_LINES (ORDER_ID, ORDER_LINE_AMOUNT, ORDER_LINE_DESCRIPTION)
    SELECT O.ORDER_ID, TO_NUMBER(REPLACE(ORDER_LINE_AMOUNT, ',', '')), B.ORDER_DESCRIPTION
    FROM BCM_ORDER_MGT B
    JOIN ORDERS O ON B.ORDER_REF = O.ORDER_REF;
    
    COMMIT;
END MIGRATE_BCM_DATA;

EXEC MIGRATE_BCM_DATA;