CREATE OR REPLACE PROCEDURE GET_SUPPLIER_ORDER_SUMMARY 
IS
    CUR SYS_REFCURSOR;
BEGIN
    -- Open Cursor to Fetch Data
    OPEN CUR FOR 
        SELECT 
            INITCAP(S.SUPPLIER_NAME) AS SUPPLIER_NAME,  -- Supplier Name in Title Case
            TO_CHAR(O.ORDER_DATE, 'YYYY-MM') AS ORDER_MONTH,  -- Group by Month-Year
            COUNT(O.ORDER_ID) AS TOTAL_ORDERS,  -- Count Orders
            TO_CHAR(SUM(O.ORDER_TOTAL_AMOUNT), '99,999,990.00') AS TOTAL_AMOUNT_ORDERED  -- Sum Order Total Amount
        FROM ORDERS O
        JOIN SUPPLIERS S ON O.SUPPLIER_ID = S.SUPPLIER_ID
        WHERE O.ORDER_DATE BETWEEN TO_DATE('01-JAN-2024', 'DD-MON-YYYY') 
                              AND TO_DATE('31-AUG-2024', 'DD-MON-YYYY')
        GROUP BY S.SUPPLIER_NAME, TO_CHAR(O.ORDER_DATE, 'YYYY-MM')
        ORDER BY TOTAL_ORDERS DESC;  -- Sort by Number of Orders

    -- Display Data
    DBMS_SQL.RETURN_RESULT(CUR);
END GET_SUPPLIER_ORDER_SUMMARY;
/
SET SERVEROUTPUT ON;
BEGIN
    GET_SUPPLIER_ORDER_SUMMARY;
END;
/
